spring.application.name=education-platform-backend

# H2 (dev) — remplacer par MySQL en prod si besoin
spring.datasource.url=jdbc:h2:mem:educationdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
# Réserve SQL (ex. User) : guillemets sur identifiants = noms du diagramme préservés
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

# JWT (en prod: utiliser une variable d'environnement)
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration-ms=86400000
